version: "3.7"
services:
  web-app:
    image: nginx:alpine
    networks:
      - proxy
      - front-end
    deploy:
      replicas: 6
      labels:
        xyz.tgergo.comonent: app
      placement:
        constraints:
          - node.role != manager
          - node.labels.xyz.tgergo.function != proxy
        preferences:
          - spread: node.labels.xyz.tgergo.zone
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
        reservations:
          cpus: "0.1"
          memory: 30M
      update_config:
        parallelism: 2
        delay: 5s
        monitor: 30s
        failure_action: rollback
      rollback_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s

  proxy:
    image: nginx:alpine
    depends_on:
      - web-app
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    configs:
      - source: proxy-config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 4
      labels:
        xyz.tgergo.component: proxy
      placement:
        constraints:
          - node.labels.xyz.tgergo.function == proxy
        preferences:
          - spread: node.labels.xyz.tgergo.zone
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 5s
        monitor: 30s
        failure_action: rollback
      

configs:
  proxy-config:
    external: true

networks:
  proxy:
  front-end:
